import type { ContentItem } from "@/lib/types";

/** 명언 모드용 — 실제 인물의 명언 (출처 표기) */
export const KO_QUOTES: ContentItem[] = [
  {
    id: "ko-q-001",
    type: "quote",
    language: "ko",
    author: "공자",
    text: "아는 것을 안다고 하고 모르는 것을 모른다고 하는 것이 곧 아는 것이다.",
  },
  {
    id: "ko-q-002",
    type: "quote",
    language: "ko",
    author: "노자",
    text: "천 리 길도 한 걸음에서 시작된다.",
  },
  {
    id: "ko-q-003",
    type: "quote",
    language: "ko",
    author: "소크라테스",
    text: "너 자신을 알라.",
  },
  {
    id: "ko-q-004",
    type: "quote",
    language: "ko",
    author: "소크라테스",
    text: "성찰하지 않는 삶은 살 가치가 없다.",
  },
  {
    id: "ko-q-005",
    type: "quote",
    language: "ko",
    author: "아리스토텔레스",
    text: "우리는 반복적으로 행하는 것의 결과다. 그러므로 탁월함은 행동이 아니라 습관이다.",
  },
  {
    id: "ko-q-006",
    type: "quote",
    language: "ko",
    author: "플라톤",
    text: "필요는 발명의 어머니다.",
  },
  {
    id: "ko-q-007",
    type: "quote",
    language: "ko",
    author: "세네카",
    text: "운이란 준비가 기회를 만나는 것이다.",
  },
  {
    id: "ko-q-008",
    type: "quote",
    language: "ko",
    author: "마르쿠스 아우렐리우스",
    text: "네 생각이 곧 너의 삶을 만든다.",
  },
  {
    id: "ko-q-009",
    type: "quote",
    language: "ko",
    author: "공자",
    text: "잘못을 하고도 고치지 않는 것, 그것이 진짜 잘못이다.",
  },
  {
    id: "ko-q-010",
    type: "quote",
    language: "ko",
    author: "공자",
    text: "자신이 원하지 않는 것을 남에게 행하지 말라.",
  },
  {
    id: "ko-q-011",
    type: "quote",
    language: "ko",
    author: "노자",
    text: "남을 아는 것은 지혜이고, 자신을 아는 것은 깨달음이다.",
  },
  {
    id: "ko-q-012",
    type: "quote",
    language: "ko",
    author: "아인슈타인",
    text: "상상력은 지식보다 중요하다.",
  },
  {
    id: "ko-q-013",
    type: "quote",
    language: "ko",
    author: "아인슈타인",
    text: "삶을 사는 데는 오직 두 가지 방법이 있다. 하나는 아무것도 기적이 아닌 것처럼, 다른 하나는 모든 것이 기적인 것처럼 사는 것이다.",
  },
  {
    id: "ko-q-014",
    type: "quote",
    language: "ko",
    author: "에디슨",
    text: "천재는 1퍼센트의 영감과 99퍼센트의 노력으로 이루어진다.",
  },
  {
    id: "ko-q-015",
    type: "quote",
    language: "ko",
    author: "링컨",
    text: "국민의, 국민에 의한, 국민을 위한 정부는 결코 지상에서 사라지지 않을 것이다.",
  },
  {
    id: "ko-q-016",
    type: "quote",
    language: "ko",
    author: "간디",
    text: "세상에서 보고 싶은 변화가 있다면, 네가 그 변화가 되어라.",
  },
  {
    id: "ko-q-017",
    type: "quote",
    language: "ko",
    author: "괴테",
    text: "무엇을 할 수 있는지 무엇을 꿈꿀 수 있는지, 그것을 시작하라. 대담함 속에 천재성과 힘과 마법이 깃들어 있다.",
  },
  {
    id: "ko-q-018",
    type: "quote",
    language: "ko",
    author: "니체",
    text: "우리를 죽이지 못하는 것은 우리를 더 강하게 만든다.",
  },
  {
    id: "ko-q-019",
    type: "quote",
    language: "ko",
    author: "니체",
    text: "춤추는 별을 낳으려면 내면에 혼돈을 품고 있어야 한다.",
  },
  {
    id: "ko-q-020",
    type: "quote",
    language: "ko",
    author: "톨스토이",
    text: "모두가 세상을 바꿀 생각을 하지만, 누구도 자기 자신을 바꿀 생각은 하지 않는다.",
  },
  {
    id: "ko-q-021",
    type: "quote",
    language: "ko",
    author: "헬렌 켈러",
    text: "세상에서 가장 아름답고 소중한 것은 보이거나 만져지지 않는다. 오직 마음으로 느껴야 한다.",
  },
  {
    id: "ko-q-022",
    type: "quote",
    language: "ko",
    author: "헬렌 켈러",
    text: "혼자서는 적은 일밖에 할 수 없지만, 함께라면 많은 일을 할 수 있다.",
  },
  {
    id: "ko-q-023",
    type: "quote",
    language: "ko",
    author: "셰익스피어",
    text: "사느냐 죽느냐, 그것이 문제로다.",
  },
  {
    id: "ko-q-024",
    type: "quote",
    language: "ko",
    author: "셰익스피어",
    text: "무엇보다도 너 자신에게 진실하라.",
  },
  {
    id: "ko-q-025",
    type: "quote",
    language: "ko",
    author: "데카르트",
    text: "나는 생각한다, 고로 존재한다.",
  },
  {
    id: "ko-q-026",
    type: "quote",
    language: "ko",
    author: "베이컨",
    text: "아는 것이 힘이다.",
  },
  {
    id: "ko-q-027",
    type: "quote",
    language: "ko",
    author: "벤저민 프랭클린",
    text: "오늘 할 수 있는 일을 내일로 미루지 말라.",
  },
  {
    id: "ko-q-028",
    type: "quote",
    language: "ko",
    author: "벤저민 프랭클린",
    text: "준비에 실패하는 것은 실패를 준비하는 것이다.",
  },
  {
    id: "ko-q-029",
    type: "quote",
    language: "ko",
    author: "마크 트웨인",
    text: "20년 후 당신은 했던 일보다 하지 않은 일로 인해 더 후회하게 될 것이다.",
  },
  {
    id: "ko-q-030",
    type: "quote",
    language: "ko",
    author: "마크 트웨인",
    text: "용기란 두려움이 없는 것이 아니라 두려움을 이겨내는 것이다.",
  },
  {
    id: "ko-q-031",
    type: "quote",
    language: "ko",
    author: "맹자",
    text: "하늘이 장차 큰 임무를 어떤 사람에게 내리려 할 때는 반드시 먼저 그 마음과 뜻을 괴롭게 한다.",
  },
  {
    id: "ko-q-032",
    type: "quote",
    language: "ko",
    author: "장자",
    text: "우물 안 개구리에게는 바다를 말할 수 없다.",
  },
  {
    id: "ko-q-033",
    type: "quote",
    language: "ko",
    author: "쇼펜하우어",
    text: "모든 진리는 세 단계를 거친다. 처음에는 조롱당하고, 다음에는 격렬히 반대받으며, 마지막에는 자명한 것으로 받아들여진다.",
  },
  {
    id: "ko-q-034",
    type: "quote",
    language: "ko",
    author: "칸트",
    text: "네 의지의 준칙이 항상 보편적 법칙이 되도록 행동하라.",
  },
  {
    id: "ko-q-035",
    type: "quote",
    language: "ko",
    author: "갈릴레오",
    text: "그래도 지구는 돈다.",
  },
  {
    id: "ko-q-036",
    type: "quote",
    language: "ko",
    author: "뉴턴",
    text: "내가 더 멀리 보았다면, 그것은 거인들의 어깨 위에 서 있었기 때문이다.",
  },
  {
    id: "ko-q-037",
    type: "quote",
    language: "ko",
    author: "다윈",
    text: "살아남는 것은 가장 강한 종도, 가장 똑똑한 종도 아니라 변화에 가장 잘 적응하는 종이다.",
  },
  {
    id: "ko-q-038",
    type: "quote",
    language: "ko",
    author: "루스벨트",
    text: "우리가 두려워해야 할 것은 두려움 그 자체뿐이다.",
  },
  {
    id: "ko-q-039",
    type: "quote",
    language: "ko",
    author: "에이브러햄 링컨",
    text: "미래를 예측하는 가장 좋은 방법은 그것을 만들어내는 것이다.",
  },
  {
    id: "ko-q-040",
    type: "quote",
    language: "ko",
    author: "소크라테스",
    text: "지혜는 경이로움에서 시작된다.",
  },
  {
    id: "ko-q-041",
    type: "quote",
    language: "ko",
    author: "아리스토텔레스",
    text: "남을 아는 것이 지혜라면, 자신을 아는 것은 진정한 지혜다.",
  },
  {
    id: "ko-q-042",
    type: "quote",
    language: "ko",
    author: "공자",
    text: "배우기만 하고 생각하지 않으면 얻는 것이 없고, 생각만 하고 배우지 않으면 위태롭다.",
  },
  {
    id: "ko-q-043",
    type: "quote",
    language: "ko",
    author: "노자",
    text: "족함을 아는 자가 부유하다.",
  },
  {
    id: "ko-q-044",
    type: "quote",
    language: "ko",
    author: "세네카",
    text: "우리가 감히 하지 못하는 것은 어려워서가 아니라, 감히 하지 않기에 어려운 것이다.",
  },
  {
    id: "ko-q-045",
    type: "quote",
    language: "ko",
    author: "마르쿠스 아우렐리우스",
    text: "행복한 삶을 사는 데 필요한 것은 거의 없다. 그것은 모두 너 자신 안에, 너의 사고방식에 달려 있다.",
  },
  {
    id: "ko-q-046",
    type: "quote",
    language: "ko",
    author: "괴테",
    text: "아는 것만으로는 충분하지 않다. 적용해야 한다. 의지만으로는 충분하지 않다. 행동해야 한다.",
  },
  {
    id: "ko-q-047",
    type: "quote",
    language: "ko",
    author: "에디슨",
    text: "나는 실패한 것이 아니다. 단지 효과가 없는 만 가지 방법을 발견했을 뿐이다.",
  },
  {
    id: "ko-q-048",
    type: "quote",
    language: "ko",
    author: "헤라클레이토스",
    text: "같은 강물에 두 번 발을 담글 수는 없다.",
  },
  {
    id: "ko-q-049",
    type: "quote",
    language: "ko",
    author: "히포크라테스",
    text: "인생은 짧고 의술은 길다.",
  },
  {
    id: "ko-q-050",
    type: "quote",
    language: "ko",
    author: "톨스토이",
    text: "가장 중요한 때는 바로 지금이고, 가장 중요한 사람은 지금 함께 있는 사람이며, 가장 중요한 일은 지금 곁에 있는 이에게 선을 행하는 것이다.",
  },
];
