import type { ContentItem } from "@/lib/types";

/** 문장 모드용 — 자연스러운 한국어 연습 문장 */
export const KO_SENTENCES: ContentItem[] = [
  { id: "ko-s-001", type: "sentence", language: "ko", text: "오늘은 날씨가 맑아서 산책하기에 좋은 날이다." },
  { id: "ko-s-002", type: "sentence", language: "ko", text: "아침에 마시는 따뜻한 커피 한 잔이 하루를 깨운다." },
  { id: "ko-s-003", type: "sentence", language: "ko", text: "주말에는 집에서 책을 읽으며 조용히 쉬고 싶다." },
  { id: "ko-s-004", type: "sentence", language: "ko", text: "봄이 오면 거리마다 벚꽃이 활짝 피어난다." },
  { id: "ko-s-005", type: "sentence", language: "ko", text: "저녁을 먹은 뒤 가족과 함께 동네를 한 바퀴 걸었다." },
  { id: "ko-s-006", type: "sentence", language: "ko", text: "오늘 회의에서 좋은 의견이 많이 나와서 기뻤다." },
  { id: "ko-s-007", type: "sentence", language: "ko", text: "비가 오는 날에는 따뜻한 국물 요리가 생각난다." },
  { id: "ko-s-008", type: "sentence", language: "ko", text: "새로 시작한 운동 덕분에 몸이 한결 가벼워졌다." },
  { id: "ko-s-009", type: "sentence", language: "ko", text: "가을 하늘은 높고 바람은 시원하게 불어온다." },
  { id: "ko-s-010", type: "sentence", language: "ko", text: "친구와 오랜만에 만나 밀린 이야기를 나누었다." },
  { id: "ko-s-011", type: "sentence", language: "ko", text: "매일 조금씩 공부하면 어느새 실력이 늘어난다." },
  { id: "ko-s-012", type: "sentence", language: "ko", text: "주방에서 갓 지은 밥 냄새가 온 집안에 퍼졌다." },
  { id: "ko-s-013", type: "sentence", language: "ko", text: "여름밤에는 창문을 열고 별을 바라보는 것이 좋다." },
  { id: "ko-s-014", type: "sentence", language: "ko", text: "퇴근길 지하철은 사람이 많아 늘 붐비곤 한다." },
  { id: "ko-s-015", type: "sentence", language: "ko", text: "오늘은 일찍 자고 내일 아침을 상쾌하게 맞고 싶다." },
  { id: "ko-s-016", type: "sentence", language: "ko", text: "작은 화분에 물을 주는 일이 하루의 습관이 되었다." },
  { id: "ko-s-017", type: "sentence", language: "ko", text: "겨울이 다가오면 따뜻한 차가 더 자주 생각난다." },
  { id: "ko-s-018", type: "sentence", language: "ko", text: "주말 아침의 느긋한 시간이 가장 마음에 든다." },
  { id: "ko-s-019", type: "sentence", language: "ko", text: "새로운 일을 배우는 것은 언제나 설레는 일이다." },
  { id: "ko-s-020", type: "sentence", language: "ko", text: "바다를 바라보고 있으면 마음이 편안해진다." },
  { id: "ko-s-021", type: "sentence", language: "ko", text: "오늘 점심에는 가까운 식당에서 김치찌개를 먹었다." },
  { id: "ko-s-022", type: "sentence", language: "ko", text: "비 온 뒤의 맑은 공기는 정말 상쾌하게 느껴진다." },
  { id: "ko-s-023", type: "sentence", language: "ko", text: "잠들기 전에 일기를 쓰면 하루가 정리되는 기분이다." },
  { id: "ko-s-024", type: "sentence", language: "ko", text: "오랜만에 영화를 보니 시간 가는 줄 몰랐다." },
  { id: "ko-s-025", type: "sentence", language: "ko", text: "이번 주말에는 어디로 여행을 떠날까 고민 중이다." },
  { id: "ko-s-026", type: "sentence", language: "ko", text: "햇살이 좋은 오후에는 빨래가 금방 마른다." },
  { id: "ko-s-027", type: "sentence", language: "ko", text: "운동을 마치고 마시는 시원한 물 한 잔이 달다." },
  { id: "ko-s-028", type: "sentence", language: "ko", text: "오늘은 어떤 음악을 들으며 일할까 고르고 있다." },
  { id: "ko-s-029", type: "sentence", language: "ko", text: "산 정상에 오르니 시원한 바람이 땀을 식혀 주었다." },
  { id: "ko-s-030", type: "sentence", language: "ko", text: "할 일을 미리 적어 두면 마음이 한결 가벼워진다." },
  { id: "ko-s-031", type: "sentence", language: "ko", text: "동네 빵집에서 갓 구운 빵을 사 오는 길이 즐겁다." },
  { id: "ko-s-032", type: "sentence", language: "ko", text: "오늘 하루도 큰 탈 없이 무사히 지나가 다행이다." },
  { id: "ko-s-033", type: "sentence", language: "ko", text: "취미로 시작한 그림이 이제는 큰 즐거움이 되었다." },
  { id: "ko-s-034", type: "sentence", language: "ko", text: "이른 아침의 거리는 조용하고 공기가 맑다." },
  { id: "ko-s-035", type: "sentence", language: "ko", text: "오늘은 무슨 요리를 해 먹을지 아직 정하지 못했다." },
  { id: "ko-s-036", type: "sentence", language: "ko", text: "오래 미뤄 둔 책을 드디어 끝까지 다 읽었다." },
  { id: "ko-s-037", type: "sentence", language: "ko", text: "낙엽이 쌓인 길을 걸으면 가을이 깊어 감을 느낀다." },
  { id: "ko-s-038", type: "sentence", language: "ko", text: "오늘 배운 내용을 잊지 않도록 다시 정리해 두었다." },
  { id: "ko-s-039", type: "sentence", language: "ko", text: "주말 농구 모임에서 땀을 흠뻑 흘리고 돌아왔다." },
  { id: "ko-s-040", type: "sentence", language: "ko", text: "창밖으로 첫눈이 내리는 모습을 한참 바라보았다." },
  { id: "ko-s-041", type: "sentence", language: "ko", text: "오늘은 마음먹고 방 정리를 깨끗하게 끝냈다." },
  { id: "ko-s-042", type: "sentence", language: "ko", text: "따뜻한 햇볕 아래에서 고양이가 졸고 있었다." },
  { id: "ko-s-043", type: "sentence", language: "ko", text: "오랜만에 손편지를 쓰니 마음이 따뜻해졌다." },
  { id: "ko-s-044", type: "sentence", language: "ko", text: "출근 전에 잠깐 스트레칭을 하면 몸이 풀린다." },
  { id: "ko-s-045", type: "sentence", language: "ko", text: "어떤 일이든 꾸준히 하면 결국 좋은 결과가 따른다." },
  { id: "ko-s-046", type: "sentence", language: "ko", text: "저녁 노을이 하늘을 붉게 물들이는 모습이 아름답다." },
  { id: "ko-s-047", type: "sentence", language: "ko", text: "오늘은 일이 잘 풀려서 기분 좋게 하루를 마쳤다." },
  { id: "ko-s-048", type: "sentence", language: "ko", text: "주말 아침에 시장에 들러 신선한 채소를 샀다." },
  { id: "ko-s-049", type: "sentence", language: "ko", text: "잠시 눈을 감고 깊게 숨을 쉬니 마음이 차분해졌다." },
  { id: "ko-s-050", type: "sentence", language: "ko", text: "내일은 또 어떤 좋은 일이 기다리고 있을까 궁금하다." },
];
