import type { ContentItem } from "@/lib/types";

/** Quote-mode — real quotes from historical/public figures (attributed) */
export const EN_QUOTES: ContentItem[] = [
  { id: "en-q-001", type: "quote", language: "en", author: "Confucius", text: "It does not matter how slowly you go as long as you do not stop." },
  { id: "en-q-002", type: "quote", language: "en", author: "Lao Tzu", text: "A journey of a thousand miles begins with a single step." },
  { id: "en-q-003", type: "quote", language: "en", author: "Socrates", text: "The only true wisdom is in knowing you know nothing." },
  { id: "en-q-004", type: "quote", language: "en", author: "Aristotle", text: "Knowing yourself is the beginning of all wisdom." },
  { id: "en-q-005", type: "quote", language: "en", author: "Marcus Aurelius", text: "You have power over your mind - not outside events. Realize this, and you will find strength." },
  { id: "en-q-006", type: "quote", language: "en", author: "Seneca", text: "Luck is what happens when preparation meets opportunity." },
  { id: "en-q-007", type: "quote", language: "en", author: "Plato", text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light." },
  { id: "en-q-008", type: "quote", language: "en", author: "Abraham Lincoln", text: "Whatever you are, be a good one." },
  { id: "en-q-009", type: "quote", language: "en", author: "Albert Einstein", text: "Imagination is more important than knowledge." },
  { id: "en-q-010", type: "quote", language: "en", author: "Mahatma Gandhi", text: "Live as if you were to die tomorrow. Learn as if you were to live forever." },
  { id: "en-q-011", type: "quote", language: "en", author: "Johann Wolfgang von Goethe", text: "Knowing is not enough; we must apply. Willing is not enough; we must do." },
  { id: "en-q-012", type: "quote", language: "en", author: "Friedrich Nietzsche", text: "That which does not kill us makes us stronger." },
  { id: "en-q-013", type: "quote", language: "en", author: "Leo Tolstoy", text: "Everyone thinks of changing the world, but no one thinks of changing himself." },
  { id: "en-q-014", type: "quote", language: "en", author: "Helen Keller", text: "Alone we can do so little; together we can do so much." },
  { id: "en-q-015", type: "quote", language: "en", author: "Thomas Edison", text: "Genius is one percent inspiration and ninety-nine percent perspiration." },
  { id: "en-q-016", type: "quote", language: "en", author: "William Shakespeare", text: "We know what we are, but know not what we may be." },
  { id: "en-q-017", type: "quote", language: "en", author: "Rene Descartes", text: "I think, therefore I am." },
  { id: "en-q-018", type: "quote", language: "en", author: "Mark Twain", text: "The secret of getting ahead is getting started." },
  { id: "en-q-019", type: "quote", language: "en", author: "Ralph Waldo Emerson", text: "What lies behind us and what lies before us are tiny matters compared to what lies within us." },
  { id: "en-q-020", type: "quote", language: "en", author: "Henry David Thoreau", text: "Go confidently in the direction of your dreams. Live the life you have imagined." },
  { id: "en-q-021", type: "quote", language: "en", author: "Benjamin Franklin", text: "An investment in knowledge pays the best interest." },
  { id: "en-q-022", type: "quote", language: "en", author: "Theodore Roosevelt", text: "Believe you can and you're halfway there." },
  { id: "en-q-023", type: "quote", language: "en", author: "Eleanor Roosevelt", text: "The future belongs to those who believe in the beauty of their dreams." },
  { id: "en-q-024", type: "quote", language: "en", author: "Aristotle", text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit." },
  { id: "en-q-025", type: "quote", language: "en", author: "Confucius", text: "Choose a job you love, and you will never have to work a day in your life." },
  { id: "en-q-026", type: "quote", language: "en", author: "Marcus Aurelius", text: "The happiness of your life depends upon the quality of your thoughts." },
  { id: "en-q-027", type: "quote", language: "en", author: "Seneca", text: "It is not that we have a short time to live, but that we waste a lot of it." },
  { id: "en-q-028", type: "quote", language: "en", author: "Mahatma Gandhi", text: "The weak can never forgive. Forgiveness is the attribute of the strong." },
  { id: "en-q-029", type: "quote", language: "en", author: "Albert Einstein", text: "A person who never made a mistake never tried anything new." },
  { id: "en-q-030", type: "quote", language: "en", author: "Friedrich Nietzsche", text: "He who has a why to live for can bear almost any how." },
  { id: "en-q-031", type: "quote", language: "en", author: "Oscar Wilde", text: "Be yourself; everyone else is already taken." },
  { id: "en-q-032", type: "quote", language: "en", author: "Oscar Wilde", text: "We are all in the gutter, but some of us are looking at the stars." },
  { id: "en-q-033", type: "quote", language: "en", author: "Mark Twain", text: "Kindness is the language which the deaf can hear and the blind can see." },
  { id: "en-q-034", type: "quote", language: "en", author: "Benjamin Franklin", text: "Tell me and I forget. Teach me and I remember. Involve me and I learn." },
  { id: "en-q-035", type: "quote", language: "en", author: "Aristotle", text: "Patience is bitter, but its fruit is sweet." },
  { id: "en-q-036", type: "quote", language: "en", author: "Lao Tzu", text: "When I let go of what I am, I become what I might be." },
  { id: "en-q-037", type: "quote", language: "en", author: "Plato", text: "The first and greatest victory is to conquer yourself." },
  { id: "en-q-038", type: "quote", language: "en", author: "Henry David Thoreau", text: "It's not what you look at that matters, it's what you see." },
  { id: "en-q-039", type: "quote", language: "en", author: "Ralph Waldo Emerson", text: "Do not go where the path may lead, go instead where there is no path and leave a trail." },
  { id: "en-q-040", type: "quote", language: "en", author: "Helen Keller", text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart." },
  { id: "en-q-041", type: "quote", language: "en", author: "Theodore Roosevelt", text: "Do what you can, with what you have, where you are." },
  { id: "en-q-042", type: "quote", language: "en", author: "Leonardo da Vinci", text: "Simplicity is the ultimate sophistication." },
  { id: "en-q-043", type: "quote", language: "en", author: "Nelson Mandela", text: "It always seems impossible until it's done." },
  { id: "en-q-044", type: "quote", language: "en", author: "Vincent van Gogh", text: "Great things are done by a series of small things brought together." },
  { id: "en-q-045", type: "quote", language: "en", author: "Winston Churchill", text: "Success is not final, failure is not fatal: it is the courage to continue that counts." },
  { id: "en-q-046", type: "quote", language: "en", author: "Confucius", text: "Our greatest glory is not in never falling, but in rising every time we fall." },
  { id: "en-q-047", type: "quote", language: "en", author: "Seneca", text: "Every new beginning comes from some other beginning's end." },
  { id: "en-q-048", type: "quote", language: "en", author: "Marcus Aurelius", text: "Waste no more time arguing about what a good man should be. Be one." },
  { id: "en-q-049", type: "quote", language: "en", author: "Socrates", text: "An unexamined life is not worth living." },
  { id: "en-q-050", type: "quote", language: "en", author: "Aristotle", text: "It is the mark of an educated mind to be able to entertain a thought without accepting it." },
];
