import type { ContentItem } from "@/lib/types";

/** Sentence-mode English practice sentences */
export const EN_SENTENCES: ContentItem[] = [
  {
    id: "en-s-001",
    type: "sentence",
    language: "en",
    text: "The morning light spilled gently across the quiet kitchen table.",
  },
  {
    id: "en-s-002",
    type: "sentence",
    language: "en",
    text: "She packed a small bag and set off before the sun had fully risen.",
  },
  {
    id: "en-s-003",
    type: "sentence",
    language: "en",
    text: "A cool breeze drifted through the open window all afternoon.",
  },
  {
    id: "en-s-004",
    type: "sentence",
    language: "en",
    text: "He brewed a fresh pot of coffee and read the news in silence.",
  },
  {
    id: "en-s-005",
    type: "sentence",
    language: "en",
    text: "The garden was full of bees humming among the bright flowers.",
  },
  {
    id: "en-s-006",
    type: "sentence",
    language: "en",
    text: "We walked along the river until the streetlights flickered on.",
  },
  {
    id: "en-s-007",
    type: "sentence",
    language: "en",
    text: "Autumn leaves crunched softly beneath our boots on the trail.",
  },
  {
    id: "en-s-008",
    type: "sentence",
    language: "en",
    text: "She finished her report early and took the rest of the day off.",
  },
  {
    id: "en-s-009",
    type: "sentence",
    language: "en",
    text: "The smell of fresh bread filled the small bakery on the corner.",
  },
  {
    id: "en-s-010",
    type: "sentence",
    language: "en",
    text: "A gentle rain fell all night and washed the dusty streets clean.",
  },
  {
    id: "en-s-011",
    type: "sentence",
    language: "en",
    text: "He spent the weekend learning to play a few simple songs.",
  },
  {
    id: "en-s-012",
    type: "sentence",
    language: "en",
    text: "The children built a tall sandcastle close to the shoreline.",
  },
  {
    id: "en-s-013",
    type: "sentence",
    language: "en",
    text: "Winter arrived quietly, dusting the rooftops with soft white snow.",
  },
  {
    id: "en-s-014",
    type: "sentence",
    language: "en",
    text: "She studied late into the night before her final exam.",
  },
  {
    id: "en-s-015",
    type: "sentence",
    language: "en",
    text: "We shared a warm meal and talked until the candles burned low.",
  },
  {
    id: "en-s-016",
    type: "sentence",
    language: "en",
    text: "The old clock on the wall ticked steadily through the quiet room.",
  },
  {
    id: "en-s-017",
    type: "sentence",
    language: "en",
    text: "He planted tomatoes and herbs along the sunny side of the yard.",
  },
  {
    id: "en-s-018",
    type: "sentence",
    language: "en",
    text: "A flock of birds rose suddenly from the field at dawn.",
  },
  {
    id: "en-s-019",
    type: "sentence",
    language: "en",
    text: "She wrote a few lines in her journal before turning off the lamp.",
  },
  {
    id: "en-s-020",
    type: "sentence",
    language: "en",
    text: "The team met early to plan the tasks for the busy week ahead.",
  },
  {
    id: "en-s-021",
    type: "sentence",
    language: "en",
    text: "Sunlight danced on the surface of the calm mountain lake.",
  },
  {
    id: "en-s-022",
    type: "sentence",
    language: "en",
    text: "He fixed the squeaky door and finally got a full night of sleep.",
  },
  {
    id: "en-s-023",
    type: "sentence",
    language: "en",
    text: "The market was busy with vendors selling fresh fruit and flowers.",
  },
  {
    id: "en-s-024",
    type: "sentence",
    language: "en",
    text: "We watched the storm roll in over the hills from the porch.",
  },
  {
    id: "en-s-025",
    type: "sentence",
    language: "en",
    text: "She learned to bake a simple cake with just a few ingredients.",
  },
  {
    id: "en-s-026",
    type: "sentence",
    language: "en",
    text: "The library was quiet except for the soft turning of pages.",
  },
  {
    id: "en-s-027",
    type: "sentence",
    language: "en",
    text: "A long walk in the woods always clears my busy mind.",
  },
  {
    id: "en-s-028",
    type: "sentence",
    language: "en",
    text: "He saved a little money each month toward a future trip.",
  },
  {
    id: "en-s-029",
    type: "sentence",
    language: "en",
    text: "The first snowfall covered the garden in a thin sheet of white.",
  },
  {
    id: "en-s-030",
    type: "sentence",
    language: "en",
    text: "She practiced the piano every evening after dinner.",
  },
  {
    id: "en-s-031",
    type: "sentence",
    language: "en",
    text: "We packed sandwiches and drove out to the coast for the day.",
  },
  {
    id: "en-s-032",
    type: "sentence",
    language: "en",
    text: "The cat curled up on the warm windowsill and fell asleep.",
  },
  {
    id: "en-s-033",
    type: "sentence",
    language: "en",
    text: "Spring brought soft green buds to the bare branches outside.",
  },
  {
    id: "en-s-034",
    type: "sentence",
    language: "en",
    text: "He took careful notes during the long afternoon meeting.",
  },
  {
    id: "en-s-035",
    type: "sentence",
    language: "en",
    text: "The soup simmered slowly while we set the table for dinner.",
  },
  {
    id: "en-s-036",
    type: "sentence",
    language: "en",
    text: "A bright moon lit the path as we walked home through the park.",
  },
  {
    id: "en-s-037",
    type: "sentence",
    language: "en",
    text: "She sorted the old photographs into neat little stacks.",
  },
  {
    id: "en-s-038",
    type: "sentence",
    language: "en",
    text: "The waves rolled in steadily as the tide began to rise.",
  },
  {
    id: "en-s-039",
    type: "sentence",
    language: "en",
    text: "He learned a new word every day to improve his writing.",
  },
  {
    id: "en-s-040",
    type: "sentence",
    language: "en",
    text: "We spent the rainy afternoon reading by the crackling fire.",
  },
  {
    id: "en-s-041",
    type: "sentence",
    language: "en",
    text: "The fresh paint gave the small room a clean and cheerful look.",
  },
  {
    id: "en-s-042",
    type: "sentence",
    language: "en",
    text: "She watered the plants and opened the curtains to let in light.",
  },
  {
    id: "en-s-043",
    type: "sentence",
    language: "en",
    text: "A thin layer of frost covered the grass early in the morning.",
  },
  {
    id: "en-s-044",
    type: "sentence",
    language: "en",
    text: "He rode his bike along the quiet lane past the old farmhouse.",
  },
  {
    id: "en-s-045",
    type: "sentence",
    language: "en",
    text: "The bakery sold out of muffins before the morning rush ended.",
  },
  {
    id: "en-s-046",
    type: "sentence",
    language: "en",
    text: "We planned a quiet weekend with books, tea, and long naps.",
  },
  {
    id: "en-s-047",
    type: "sentence",
    language: "en",
    text: "The sunset painted the sky in soft shades of orange and pink.",
  },
  {
    id: "en-s-048",
    type: "sentence",
    language: "en",
    text: "She tidied her desk and felt ready to start the new project.",
  },
  {
    id: "en-s-049",
    type: "sentence",
    language: "en",
    text: "A small stream trickled through the meadow near the old bridge.",
  },
  {
    id: "en-s-050",
    type: "sentence",
    language: "en",
    text: "He closed the book, stretched, and smiled at the late hour.",
  },
];
